In [1]:
#Getting and knowing data

In [2]:
import pandas as pd
import numpy as np
import os
print(os.getcwd())

C:\Users\Admin\Documents\Knowing_DATA

In [3]:
#STEP 1 : INPUT DATA

In [4]:
df = pd.read_csv("chipotle.tsv", sep = "\t")

In [5]:
df.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [6]:
#step 2: dataset overview

In [7]:
df.shape

(4622, 5)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 490.3 KB

In [9]:
list(df.columns)

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

In [10]:
df.index

RangeIndex(start=0, stop=4622, step=1)

In [11]:
df.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [12]:
###loc and iloc // loc: location iloc: index_location

In [13]:
df.loc[(df.quantity == 15) | (df.item_name == "Chicken Bowl"), ["item_price", "choice_description"]]

     item_price                                 choice_description
4       $16.98   [Tomatillo-Red Chili Salsa (Hot), [Black Beans...
5       $10.98   [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...
13      $11.25   [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...
19       $8.75   [Tomatillo Red Chili Salsa, [Fajita Vegetables...
26       $8.49   [Roasted Chili Corn Salsa (Medium), [Pinto Bea...
...         ...                                                ...
4590    $11.25   [Roasted Chili Corn Salsa, [Rice, Black Beans,...
4591     $8.75   [Tomatillo Red Chili Salsa, [Rice, Black Beans...
4595     $8.75   [Tomatillo Green Chili Salsa, [Rice, Black Bea...
4599     $8.75       [Roasted Chili Corn Salsa, [Cheese, Lettuce]]
4604     $8.75   [Fresh Tomato Salsa, [Rice, Black Beans, Chees...

[727 rows x 2 columns]

In [14]:
df.iloc[9]

order_id                                                              5
quantity                                                              1
item_name                                                 Steak Burrito
choice_description    [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...
item_price                                                       $9.25
Name: 9, dtype: object

In [15]:
df.iloc[[9]]

,order_id,quantity,item_name,choice_description,item_price
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [16]:
df.iloc[3:5, -1]

3     $2.39
4    $16.98
Name: item_price, dtype: str

In [17]:
df.iloc[3:5, 0:-1]

,order_id,quantity,item_name,choice_description
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans..."

In [18]:
### thao tac tren data

In [19]:
df.item_price.dtype

In [20]:
### apply()
df.item_price = df.item_price.apply(lambda x : float(x.replace('$', '')))

In [21]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [24]:
df["total_price"] = df["item_price"]*df["quantity"]

In [25]:
df.head()

,order_id,quantity,item_name,choice_description,item_price,total_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96

In [27]:
## tinh tong gia trij ban duoc
df['total_price'].sum()

np.float64(39237.02)

In [34]:
## tim hang nao duoc oder nhieu nhat
c = df.groupby("item_name")["quantity"].sum()
c.sort_values()

item_name
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Crispy Tacos                               2
Salad                                      2
Steak Salad                                4
Bowl                                       4
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Veggie Soft Tacos                          8
Carnitas Crispy Tacos                      8
Chicken Salad                              9
Barbacoa Salad Bowl                       10
Barbacoa Crispy Tacos                     12
Chips and Roasted Chili-Corn Salsa        18
Veggie Salad Bowl                         18
Izze                                      20
Chips and Roasted Chili Corn Salsa        23
Barbacoa Soft Tacos                       25
Chips and Tomatillo-Red Chili Salsa       25
Nantucket Nectar                          29
Steak Salad Bowl                          31
Chips and Tomatillo-Green Chili Salsa     33
Steak Crispy Tacos                        36
Carnitas Soft Tacos                       40
Chips and Tomatillo Green Chili Salsa     45
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
6 Pack Soft Drink                         55
Steak Soft Tacos                          56
Carnitas Burrito                          60
Barbacoa Bowl                             66
Carnitas Bowl                             71
Veggie Bowl                               87
Barbacoa Burrito                          91
Veggie Burrito                            97
Side of Chips                            110
Chicken Soft Tacos                       120
Chicken Salad Bowl                       123
Canned Soda                              126
Chips and Fresh Tomato Salsa             130
Bottled Water                            211
Steak Bowl                               221
Chips                                    230
Canned Soft Drink                        351
Steak Burrito                            386
Chips and Guacamole                      506
Chicken Burrito                          591
Chicken Bowl                             761
Name: quantity, dtype: int64

In [37]:
c.sort_values(ascending = 0)

item_name
Chicken Bowl                             761
Chicken Burrito                          591
Chips and Guacamole                      506
Steak Burrito                            386
Canned Soft Drink                        351
Chips                                    230
Steak Bowl                               221
Bottled Water                            211
Chips and Fresh Tomato Salsa             130
Canned Soda                              126
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Side of Chips                            110
Veggie Burrito                            97
Barbacoa Burrito                          91
Veggie Bowl                               87
Carnitas Bowl                             71
Barbacoa Bowl                             66
Carnitas Burrito                          60
Steak Soft Tacos                          56
6 Pack Soft Drink                         55
Chicken Crispy Tacos                      50
Chips and Tomatillo Red Chili Salsa       50
Chips and Tomatillo Green Chili Salsa     45
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        36
Chips and Tomatillo-Green Chili Salsa     33
Steak Salad Bowl                          31
Nantucket Nectar                          29
Chips and Tomatillo-Red Chili Salsa       25
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        23
Izze                                      20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      8
Veggie Soft Tacos                          8
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Bowl                                       4
Steak Salad                                4
Salad                                      2
Crispy Tacos                               2
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Name: quantity, dtype: int64

In [44]:
c.sort_values(ascending = 0).head(5)

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

In [50]:
## nhung gia tri duy nhat khong lap lai
df["item_name"].value_counts().count()

np.int64(50)